
read: read_noncanonical.c
	gcc read_noncanonical.c -o read_noncanonical

write: write_noncanonical.c
	gcc write_noncanonical.c -o write_noncanonical

clean: 
	rm -f read_noncanonical
	rm -f write_noncanonical